package edu.jhu.cobra.commons.graph

import edu.jhu.cobra.commons.graph.poset.IPoset
import edu.jhu.cobra.commons.graph.poset.Label
import edu.jhu.cobra.commons.graph.storage.IStorage
import edu.jhu.cobra.commons.value.ListVal
import edu.jhu.cobra.commons.value.NumVal
import edu.jhu.cobra.commons.value.StrVal
import edu.jhu.cobra.commons.value.listVal
import edu.jhu.cobra.commons.value.numVal
import edu.jhu.cobra.commons.value.strVal
import java.io.Closeable
import java.lang.ref.SoftReference

/**
 * Abstract directed multi-graph allowing multiple edges between the same pair of
 * nodes, with integrated label-based edge visibility.
 *
 * Node IDs are user-provided mandatory strings. Edge IDs are generated by the
 * graph layer. Uses dual storage: [storage] for graph data (nodes/edges),
 * [posetStorage] for label hierarchy (labels as nodes with parent/changes properties).
 *
 * @param N The type of nodes in the graph, must extend [AbcNode].
 * @param E The type of edges in the graph, must extend [AbcEdge].
 */
@Suppress("TooManyFunctions")
abstract class AbcMultipleGraph<N : AbcNode, E : AbcEdge> :
    IGraph<N, E>,
    IPoset,
    Closeable {
    abstract val storage: IStorage
    abstract val posetStorage: IStorage

    // Edge index: (src, dst, type) → edgeId for O(1) findEdge
    private val edgeIndex = HashMap<Triple<NodeID, NodeID, String>, String>()
    private var edgeIndexReady = false

    // Label ID cache: Label.core ↔ storage label nodeId
    private val labelIdCache = HashMap<String, NodeID>()
    private var labelIdCacheReady = false

    // SoftReference caches: allow GC to reclaim unused wrapper objects
    private val nodeCache = HashMap<NodeID, SoftReference<N>>()
    private val edgeCache = HashMap<String, SoftReference<E>>()

    override val nodeIDs: Set<NodeID>
        get() = storage.nodeIDs

    protected abstract fun newNodeObj(nodeId: NodeID): N

    protected abstract fun newEdgeObj(edgeId: String): E

    private fun cachedNode(nodeId: NodeID): N {
        nodeCache[nodeId]?.get()?.let { return it }
        val node = newNodeObj(nodeId)
        nodeCache[nodeId] = SoftReference(node)
        return node
    }

    private fun cachedEdge(edgeId: String): E {
        edgeCache[edgeId]?.get()?.let { return it }
        val edge = newEdgeObj(edgeId)
        edgeCache[edgeId] = SoftReference(edge)
        return edge
    }

    private fun ensureEdgeIndex() {
        if (edgeIndexReady) return
        for (edgeId in storage.edgeIDs) {
            val src = storage.getEdgeSrc(edgeId)
            val dst = storage.getEdgeDst(edgeId)
            val type = storage.getEdgeType(edgeId)
            edgeIndex[Triple(src, dst, type)] = edgeId
        }
        edgeIndexReady = true
    }

    // O(1) edge lookup via index
    private fun findEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
    ): String? {
        ensureEdgeIndex()
        return edgeIndex[Triple(src, dst, type)]
    }

    // region IPoset — write-through to posetStorage (labels as nodes)

    private val queryCache = mutableMapOf<Pair<Label, Label>, Int?>()

    // Resolves Label.core → posetStorage label node ID
    private fun resolveLabelStorageId(label: Label): NodeID? {
        ensureLabelIdCache()
        return labelIdCache[label.core]
    }

    private fun ensureLabelIdCache() {
        if (labelIdCacheReady) return
        for (nodeId in posetStorage.nodeIDs) {
            val labelCore = posetStorage.getNodeProperty(nodeId, "label") as? StrVal
            if (labelCore != null) {
                labelIdCache[labelCore.core] = nodeId
            }
        }
        labelIdCacheReady = true
    }

    // Creates label node if not exists, returns its posetStorage node ID
    private fun ensureLabelNode(label: Label): NodeID {
        resolveLabelStorageId(label)?.let { return it }
        val nodeId = label.core
        posetStorage.addNode(nodeId, mapOf("label" to label.core.strVal))
        labelIdCache[label.core] = nodeId
        return nodeId
    }

    override val allLabels: Set<Label>
        get() {
            ensureLabelIdCache()
            val labels = labelIdCache.keys.mapTo(LinkedHashSet()) { Label(it) }
            return labels + Label.INFIMUM + Label.SUPREMUM
        }

    override var Label.parents: Map<String, Label>
        get() {
            val nodeId = resolveLabelStorageId(this) ?: return emptyMap()
            val result = LinkedHashMap<String, Label>()
            for (edgeId in posetStorage.getOutgoingEdges(nodeId)) {
                val parentNodeId = posetStorage.getEdgeDst(edgeId)
                val name = posetStorage.getEdgeType(edgeId)
                val parentLabel = Label(parentNodeId)
                result[name] = parentLabel
            }
            return result
        }
        set(value) {
            val nodeId = ensureLabelNode(this)
            // Remove all existing parent edges
            for (edgeId in posetStorage.getOutgoingEdges(nodeId).toList()) {
                posetStorage.deleteEdge(edgeId)
            }
            // Create new parent edges: this → parent, type = name
            for ((name, parentLabel) in value) {
                val parentNodeId = ensureLabelNode(parentLabel)
                val edgeId = "$nodeId-$name-$parentNodeId"
                posetStorage.addEdge(nodeId, parentNodeId, edgeId, name, emptyMap())
            }
            queryCache.clear()
        }

    override val Label.ancestors: Sequence<Label>
        get() =
            sequence {
                val startNodeId = resolveLabelStorageId(this@ancestors) ?: return@sequence
                val visited = hashSetOf<NodeID>()
                val stack = ArrayDeque<NodeID>().also { it.add(startNodeId) }
                while (stack.isNotEmpty()) {
                    val currentNodeId = stack.removeFirst()
                    if (!visited.add(currentNodeId)) continue
                    for (edgeId in posetStorage.getOutgoingEdges(currentNodeId)) {
                        val parentNodeId = posetStorage.getEdgeDst(edgeId)
                        val parentLabel = Label(parentNodeId)
                        yield(parentLabel)
                        stack.add(parentNodeId)
                    }
                }
            }

    override var Label.changes: Set<String>
        get() {
            val nodeId = resolveLabelStorageId(this) ?: return emptySet()
            val raw = posetStorage.getNodeProperty(nodeId, PROP_CHANGES) as? ListVal ?: return emptySet()
            return raw.map { (it as StrVal).core }.toSet()
        }
        set(value) {
            val nodeId = ensureLabelNode(this)
            if (value.isEmpty()) {
                posetStorage.setNodeProperties(nodeId, mapOf(PROP_CHANGES to null))
            } else {
                posetStorage.setNodeProperties(nodeId, mapOf(PROP_CHANGES to value.map { it.strVal }.listVal))
            }
        }

    override fun Label.compareTo(other: Label): Int? {
        if (this == other) return 0
        if (this == Label.SUPREMUM || other == Label.INFIMUM) return 1
        if (other == Label.SUPREMUM || this == Label.INFIMUM) return -1
        if (this to other in queryCache) return queryCache[this to other]
        if (other to this in queryCache) return queryCache[other to this]?.let { -it }
        other.ancestors.forEach { label ->
            if (label != this) return@forEach
            queryCache[this to other] = 1
            return 1
        }
        this.ancestors.forEach { label ->
            if (label != other) return@forEach
            queryCache[this to other] = -1
            return -1
        }
        return null
    }

    // endregion

    // region Node operations

    override fun addNode(withID: NodeID): N {
        if (storage.containsNode(withID)) throw EntityAlreadyExistException(withID)
        storage.addNode(withID, emptyMap())
        return cachedNode(withID)
    }

    override fun getNode(whoseID: NodeID): N? {
        if (!storage.containsNode(whoseID)) return null
        return cachedNode(whoseID)
    }

    override fun containNode(whoseID: NodeID): Boolean = storage.containsNode(whoseID)

    override fun delNode(whoseID: NodeID) {
        if (!storage.containsNode(whoseID)) return
        val allEdges = (storage.getIncomingEdges(whoseID) + storage.getOutgoingEdges(whoseID)).toList()
        for (edgeId in allEdges) {
            val src = storage.getEdgeSrc(edgeId)
            val dst = storage.getEdgeDst(edgeId)
            val type = storage.getEdgeType(edgeId)
            edgeIndex.remove(Triple(src, dst, type))
            edgeCache.remove(edgeId)
            storage.deleteEdge(edgeId)
        }
        nodeCache.remove(whoseID)
        storage.deleteNode(whoseID)
    }

    override fun getAllNodes(doSatfy: (N) -> Boolean): Sequence<N> =
        storage.nodeIDs
            .asSequence()
            .map { cachedNode(it) }
            .filter(doSatfy)

    // endregion

    // region Edge operations

    override fun addEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
    ): E {
        if (!storage.containsNode(src)) throw EntityNotExistException(src)
        if (!storage.containsNode(dst)) throw EntityNotExistException(dst)
        val edgeId = "$src-$type-$dst"
        storage.addEdge(src, dst, edgeId, type, emptyMap())
        edgeIndex[Triple(src, dst, type)] = edgeId
        return newEdgeObj(edgeId)
    }

    open fun addEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
        label: Label,
    ): E {
        if (!storage.containsNode(src)) throw EntityNotExistException(src)
        if (!storage.containsNode(dst)) throw EntityNotExistException(dst)
        val existingEdgeId = findEdge(src, dst, type)
        val edge =
            if (existingEdgeId != null) {
                cachedEdge(existingEdgeId)
            } else {
                val edgeId = "$src-$type-$dst"
                storage.addEdge(src, dst, edgeId, type, emptyMap())
                edgeIndex[Triple(src, dst, type)] = edgeId
                newEdgeObj(edgeId)
            }
        edge.labels = edge.labels + label
        label.changes += edge.edgeId
        return edge
    }

    override fun getEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
    ): E? {
        if (!storage.containsNode(src)) return null
        if (!storage.containsNode(dst)) return null
        val edgeId = findEdge(src, dst, type) ?: return null
        return cachedEdge(edgeId)
    }

    override fun containEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
    ): Boolean {
        if (!storage.containsNode(src)) return false
        if (!storage.containsNode(dst)) return false
        return findEdge(src, dst, type) != null
    }

    override fun delEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
    ) {
        if (!storage.containsNode(src)) return
        if (!storage.containsNode(dst)) return
        val edgeId = findEdge(src, dst, type) ?: return
        edgeIndex.remove(Triple(src, dst, type))
        edgeCache.remove(edgeId)
        storage.deleteEdge(edgeId)
    }

    fun delEdge(
        src: NodeID,
        dst: NodeID,
        type: String,
        label: Label,
    ) {
        if (!storage.containsNode(src)) return
        if (!storage.containsNode(dst)) return
        val edgeId = findEdge(src, dst, type) ?: return
        val edge = cachedEdge(edgeId)
        val oldLabels = edge.labels
        val newLabels = oldLabels - label
        edge.labels = newLabels
        if (label in oldLabels) label.changes = label.changes - setOf(edgeId)
        if (newLabels.isNotEmpty()) return
        edgeIndex.remove(Triple(src, dst, type))
        edgeCache.remove(edgeId)
        storage.deleteEdge(edgeId)
    }

    override fun getAllEdges(doSatfy: (E) -> Boolean): Sequence<E> =
        storage.edgeIDs
            .asSequence()
            .map { cachedEdge(it) }
            .filter(doSatfy)

    // endregion

    // region Graph structure queries

    override fun getOutgoingEdges(of: NodeID): Sequence<E> {
        if (!storage.containsNode(of)) return emptySequence()
        return storage.getOutgoingEdges(of).asSequence().map { cachedEdge(it) }
    }

    override fun getIncomingEdges(of: NodeID): Sequence<E> {
        if (!storage.containsNode(of)) return emptySequence()
        return storage.getIncomingEdges(of).asSequence().map { cachedEdge(it) }
    }

    fun getOutgoingEdges(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<E> = getOutgoingEdges(of).filter(cond).filterVisitable(label)

    fun getIncomingEdges(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<E> = getIncomingEdges(of).filter(cond).filterVisitable(label)

    override fun getParents(
        of: NodeID,
        edgeCond: (E) -> Boolean,
    ): Sequence<N> = getIncomingEdges(of).filter(edgeCond).mapNotNull { getNode(it.srcNid) }

    override fun getChildren(
        of: NodeID,
        edgeCond: (E) -> Boolean,
    ): Sequence<N> = getOutgoingEdges(of).filter(edgeCond).mapNotNull { getNode(it.dstNid) }

    fun getChildren(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<N> = getOutgoingEdges(of, label, cond).mapNotNull { getNode(it.dstNid) }

    fun getParents(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<N> = getIncomingEdges(of, label, cond).mapNotNull { getNode(it.srcNid) }

    override fun getAncestors(
        of: NodeID,
        edgeCond: (E) -> Boolean,
    ) = sequence {
        if (!storage.containsNode(of)) return@sequence
        val visited = hashSetOf<NodeID>()
        val queue = ArrayDeque<NodeID>().apply { add(of) }
        while (queue.isNotEmpty()) {
            val currentNodeId = queue.removeFirst()
            if (!visited.add(currentNodeId)) continue
            storage.getIncomingEdges(currentNodeId).forEach { edgeId ->
                val parentNodeId = storage.getEdgeSrc(edgeId)
                val edge = cachedEdge(edgeId)
                if (!edgeCond(edge)) return@forEach
                yield(cachedNode(parentNodeId))
                queue.add(parentNodeId)
            }
        }
    }

    override fun getDescendants(
        of: NodeID,
        edgeCond: (E) -> Boolean,
    ) = sequence {
        if (!storage.containsNode(of)) return@sequence
        val visited = hashSetOf<NodeID>()
        val queue = ArrayDeque<NodeID>().apply { add(of) }
        while (queue.isNotEmpty()) {
            val currentNodeId = queue.removeFirst()
            if (!visited.add(currentNodeId)) continue
            storage.getOutgoingEdges(currentNodeId).forEach { edgeId ->
                val childNodeId = storage.getEdgeDst(edgeId)
                val edge = cachedEdge(edgeId)
                if (!edgeCond(edge)) return@forEach
                yield(cachedNode(childNodeId))
                queue.add(childNodeId)
            }
        }
    }

    fun getDescendants(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<N> =
        sequence {
            val visited = mutableSetOf<NodeID>()
            val queue = ArrayDeque<NodeID>().apply { add(of) }
            while (queue.isNotEmpty()) {
                val current = queue.removeFirst()
                getChildren(current, label, cond).forEach { child ->
                    if (visited.add(child.id)) {
                        yield(child)
                        queue.add(child.id)
                    }
                }
            }
        }

    fun getAncestors(
        of: NodeID,
        label: Label,
        cond: (E) -> Boolean = { true },
    ): Sequence<N> =
        sequence {
            val visited = mutableSetOf<NodeID>()
            val queue = ArrayDeque<NodeID>().apply { add(of) }
            while (queue.isNotEmpty()) {
                val current = queue.removeFirst()
                getParents(current, label, cond).forEach { parent ->
                    if (visited.add(parent.id)) {
                        yield(parent)
                        queue.add(parent.id)
                    }
                }
            }
        }

    // endregion

    /**
     * Filters edges by label visibility: visitable if at least one label is
     * equal to or below `by` in the hierarchy, excluding labels covered by
     * a higher visitable label.
     */
    private fun Sequence<E>.filterVisitable(by: Label): Sequence<E> {
        if (by == Label.SUPREMUM) return this
        val edgesWithLabels = this.map { e -> e to e.labels }.toList()
        val allVisitable =
            edgesWithLabels
                .flatMap { (_, labels) ->
                    labels.filter { l ->
                        by == l || by.compareTo(l)?.let { it > 0 } ?: false
                    }
                }.toSet()
        val allNotCovered =
            allVisitable.filter { cur ->
                !allVisitable.any { other ->
                    other != cur && other.compareTo(cur)?.let { it > 0 } ?: false
                }
            }.toSet()
        return edgesWithLabels
            .filter { (_, labels) ->
                labels.any { it in allNotCovered }
            }.map { it.first }
            .asSequence()
    }

    override fun close() {
        edgeIndex.clear()
        edgeIndexReady = false
        labelIdCache.clear()
        labelIdCacheReady = false
        queryCache.clear()
        nodeCache.clear()
        edgeCache.clear()
    }

    companion object {
        private const val PROP_CHANGES = "changes"
    }
}
