[versions]
kotlin = "2.0.21"
kotlinx = "1.10.2"
kover = "0.9.1"
javaSource = "8"
javaTarget = "8"
cobra-commons-value = "0.1.0"
mapdb = "3.0.9"
jgrapht = "1.5.0"
neo4j = "3.5.35"


[libraries]
neo4j-core = { module = "org.neo4j:neo4j", version.ref = "neo4j" }
mapdb-core = { module = "org.mapdb:mapdb", version.ref = "mapdb" }
jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
cobra-commons-value = { module = "com.github.jhu-seclab-cobra:commons-value", version.ref = "cobra-commons-value" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }