package edu.jhu.cobra.commons.graph.storage

import edu.jhu.cobra.commons.graph.AccessClosedStorageException
import edu.jhu.cobra.commons.graph.EntityNotExistException
import edu.jhu.cobra.commons.value.IValue
import java.io.Closeable

/**
 * Core interface for graph storage with String-based semantic IDs.
 *
 * Manages nodes and edges identified by semantic `String` IDs (provided by callers for nodes,
 * generated by the graph layer for edges). Implementations may internally use integer IDs
 * for compactness and indexing — this is a pure implementation detail. All entity IDs must
 * be uniquely identifiable and deterministically retrievable.
 *
 * @see NativeStorageImpl
 * @see NativeConcurStorageImpl
 */
@Suppress("TooManyFunctions")
interface IStorage : Closeable {
    // ============================================================================
    // NODE OPERATIONS
    // ============================================================================

    /**
     * All node IDs currently in storage.
     *
     * @throws AccessClosedStorageException If storage is closed.
     */
    val nodeIDs: Set<String>

    /**
     * Checks if a node exists.
     *
     * @param id The node ID.
     * @return True if the node exists.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun containsNode(id: String): Boolean

    /**
     * Adds a node with the given properties.
     *
     * @param nodeId The semantic node ID provided by the caller.
     * @param properties Initial property map.
     * @return The same nodeId.
     * @throws EntityAlreadyExistException If nodeId already exists.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun addNode(
        nodeId: String,
        properties: Map<String, IValue> = emptyMap(),
    ): String

    /**
     * Returns all properties of a node.
     *
     * @param id The node ID.
     * @return Property map.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun getNodeProperties(id: String): Map<String, IValue>

    /**
     * Returns a single property value of a node.
     *
     * Default delegates to [getNodeProperties]; implementations may override
     * for O(1) direct access.
     *
     * @param id The node ID.
     * @param name The property name.
     * @return The property value, or null if absent.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun getNodeProperty(
        id: String,
        name: String,
    ): IValue? = getNodeProperties(id)[name]

    /**
     * Updates properties of a node. Null values delete the corresponding property.
     *
     * @param id The node ID.
     * @param properties Property updates.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun setNodeProperties(
        id: String,
        properties: Map<String, IValue?>,
    )

    /**
     * Deletes a node and all its incident edges.
     *
     * @param id The node ID.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun deleteNode(id: String)

    // ============================================================================
    // EDGE OPERATIONS
    // ============================================================================

    /**
     * All edge IDs currently in storage.
     *
     * @throws AccessClosedStorageException If storage is closed.
     */
    val edgeIDs: Set<String>

    /**
     * Checks if an edge exists.
     *
     * @param id The edge ID.
     * @return True if the edge exists.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun containsEdge(id: String): Boolean

    /**
     * Adds an edge between two existing nodes.
     *
     * @param src The source node ID.
     * @param dst The destination node ID.
     * @param edgeId The semantic edge ID provided by the caller.
     * @param tag The edge tag name.
     * @param properties Initial property map.
     * @return The same edgeId.
     * @throws EntityNotExistException If source or destination node does not exist.
     * @throws EntityAlreadyExistException If edgeId already exists.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun addEdge(
        src: String,
        dst: String,
        edgeId: String,
        tag: String,
        properties: Map<String, IValue> = emptyMap(),
    ): String

    /**
     * Structural info of an edge: source node, destination node, and type.
     *
     * @property src The source node ID.
     * @property dst The destination node ID.
     * @property tag The edge tag name.
     */
    data class EdgeStructure(
        val src: String,
        val dst: String,
        val tag: String,
    )

    /**
     * Returns the structural info (source, destination, type) of an edge in a single lookup.
     *
     * @param id The edge ID.
     * @return The edge structure containing src, dst, and type.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeStructure(id: String): EdgeStructure

    /**
     * Returns the source node ID of an edge.
     *
     * Default delegates to [getEdgeStructure]; implementations may override for efficiency.
     *
     * @param id The edge ID.
     * @return The source node ID (String).
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeSrc(id: String): String = getEdgeStructure(id).src

    /**
     * Returns the destination node ID of an edge.
     *
     * Default delegates to [getEdgeStructure]; implementations may override for efficiency.
     *
     * @param id The edge ID.
     * @return The destination node ID (String).
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeDst(id: String): String = getEdgeStructure(id).dst

    /**
     * Returns the tag of an edge.
     *
     * Default delegates to [getEdgeStructure]; implementations may override for efficiency.
     *
     * @param id The edge ID.
     * @return The edge tag name.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeTag(id: String): String = getEdgeStructure(id).tag

    /**
     * Returns all properties of an edge.
     *
     * @param id The edge ID.
     * @return Property map.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeProperties(id: String): Map<String, IValue>

    /**
     * Returns a single property value of an edge.
     *
     * Default delegates to [getEdgeProperties]; implementations may override
     * for O(1) direct access.
     *
     * @param id The edge ID.
     * @param name The property name.
     * @return The property value, or null if absent.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun getEdgeProperty(
        id: String,
        name: String,
    ): IValue? = getEdgeProperties(id)[name]

    /**
     * Updates properties of an edge. Null values delete the corresponding property.
     *
     * @param id The edge ID.
     * @param properties Property updates.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun setEdgeProperties(
        id: String,
        properties: Map<String, IValue?>,
    )

    /**
     * Deletes an edge from storage.
     *
     * @param id The edge ID.
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If edge does not exist.
     */
    fun deleteEdge(id: String)

    // ============================================================================
    // ADJACENCY QUERIES
    // ============================================================================

    /**
     * Returns all incoming edge IDs to a node.
     *
     * @param id The node ID.
     * @return Set of incoming edge IDs (String).
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun getIncomingEdges(id: String): Set<String>

    /**
     * Returns all outgoing edge IDs from a node.
     *
     * @param id The node ID.
     * @return Set of outgoing edge IDs (String).
     * @throws AccessClosedStorageException If storage is closed.
     * @throws EntityNotExistException If node does not exist.
     */
    fun getOutgoingEdges(id: String): Set<String>

    // ============================================================================
    // METADATA OPERATIONS
    // ============================================================================

    /**
     * All metadata property names currently in storage.
     *
     * @throws AccessClosedStorageException If storage is closed.
     */
    val metaNames: Set<String>

    /**
     * Returns a metadata value by name.
     *
     * @param name The metadata property name.
     * @return The value, or null if not found.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun getMeta(name: String): IValue?

    /**
     * Sets a metadata value. Passing null deletes the property.
     *
     * @param name The metadata property name.
     * @param value The value, or null to delete.
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun setMeta(
        name: String,
        value: IValue?,
    )

    // ============================================================================
    // LIFECYCLE
    // ============================================================================

    /**
     * Removes all nodes, edges, and metadata from storage.
     *
     * @throws AccessClosedStorageException If storage is closed.
     */
    fun clear()

    /**
     * Transfers all data (nodes, edges, metadata) into [target].
     *
     * Nodes are transferred before edges to satisfy existence constraints.
     *
     * @param target The destination storage.
     */
    fun transferTo(target: IStorage)
}
