name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage reports
        run: ./gradlew :graph:test :modules:impl-mapdb:test :modules:impl-jgrapht:test :modules:impl-neo4j:test :graph:koverXmlReport :modules:impl-mapdb:koverXmlReport :modules:impl-jgrapht:koverXmlReport :modules:impl-neo4j:koverXmlReport -PexcludePerformanceTests=true

      - name: List all coverage reports (debug)
        run: find . -name report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jhu-seclab-cobra/commons-graph
          files: ./graph/build/reports/kover/report.xml,./modules/impl-mapdb/build/reports/kover/report.xml,./modules/impl-jgrapht/build/reports/kover/report.xml,./modules/impl-neo4j/build/reports/kover/report.xml
          fail_ci_if_error: true