name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage reports
        run: >-
          ./gradlew
          :jhu-seclab-cobra-commons-graph:test
          :jhu-seclab-cobra-commons-graph-impl-mapdb:test
          :jhu-seclab-cobra-commons-graph-impl-jgrapht:test
          :jhu-seclab-cobra-commons-graph-impl-neo4j:test
          :jhu-seclab-cobra-commons-graph:koverXmlReport
          :jhu-seclab-cobra-commons-graph-impl-mapdb:koverXmlReport
          :jhu-seclab-cobra-commons-graph-impl-jgrapht:koverXmlReport
          :jhu-seclab-cobra-commons-graph-impl-neo4j:koverXmlReport
          -PexcludePerformanceTests=true

      - name: List all coverage reports (debug)
        run: find . -name report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jhu-seclab-cobra/commons-graph
          files: ./commons-graph/build/reports/kover/report.xml,./commons-graph-impl-mapdb/build/reports/kover/report.xml,./commons-graph-impl-jgrapht/build/reports/kover/report.xml,./commons-graph-impl-neo4j/build/reports/kover/report.xml
          fail_ci_if_error: true